### ISSUE TITLE
talk.js - August 2016

### ISSUE THREAD

**Issue by ongmin** [SingaporeJS/organizers#32]
#### Details
- [x] Date: August 25, 2016 - Thursday
- [x] Hosts: @ongmin @jsstrn
- [x] Venue sponsor: PayPal Singapore, Suntec Tower 5
- [x] Food/drink sponsor: PayPal
#### Speakers
- [x] Performance implications of using the special arguments variable - @jhecking
- [x] Declarative vs Imperative Programming - Chris Boesch
- [x] Encouraging Kids to Code - Shannon Boesch
- If you would like to speak (this or next months), please ping!

**Note to speakers:** Add a comment to share links to your slides.
#### Organizers' to-dos
- [ ] Announce on SingaporeJS Meetup Page
- [ ] Announce on SingaporeJS Gitter
- [ ] Announce on SingaporeJS Facebook Group
- [ ] Send out a reminder one day before event to all channels listed above

\* checked boxes indicate confirmed/done

**Comment by ongmin** [comment]
> **Instructions**: Copy and paste the text below, add a comment and fill up the respective fields.

**Title of your talk**: _insert catchy title here_
**Talk description**: _tell us what you'd like to talk about_
**Presenters**: _include your GitHub handles where possible_
**Duration requested**: _lightning (5 min), default (10min + 5mins Q&A), long (15min + 5mins Q&A)_
**Deck URL** (if any): _you can add this part in later_

**Comment by jhecking** [comment]
**Title of your talk:** How avoiding arguments saved the day and improved benchmark performance by 10%
**Talk description:** Optimizing a performance critical function in the Aerospike Node.js client library improved performance of that function by 34x and resulted in a 10% increase in the client's benchmark performance. I will explore how the use of the special `arguments` variable in a variadic function can hurt performance because it prevents V8 from optimizing the code; then I will show different alternatives that prevent this problem and benchmark them to show which one performs best.
**Presenters:** Jan Hecking (@jhecking)
**Duration requested:** default (10min + 5mins Q&A)
**Deck URL (if any):** https://speakerdeck.com/jhecking/how-avoiding-arguments-saved-the-day

References:
- The blog post this talk is based upon: http://www.aerospike.com/blog/node-on-fire/
- "Optimization killers" by the bluebird project: https://github.com/petkaantonov/bluebird/wiki/Optimization-killers
