### ISSUE TITLE
talk.js - April 2017

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#44]
### Details
- [x] Event: [talk.js]()
- [x] Date: 20 April 2017
- [x] Hosts: @jsstrn
- [x] Venue sponsor: PayPal Singapore, Suntec Tower 5
- [x] Food/drink sponsor: PayPal

### Talks
- [x] PrimeReact: UI Component Library for React by Sudheer Jonna
- [x] How to Choose the Right Front-End Framework for Your Company by Chris Lienert
- [ ] _You?_

### Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

> **Title of your talk**: insert catchy title here
> **Talk description**: tell us what you'd like to talk about
> **Presenter**: include GitHub handles where possible
> **Presenter's bio**: a short introduction of yourself
> **Duration requested**: 5min, 10min, 15min
> **Deck URL (if any)**: you can add this part in later

### Propose a talk next time
Can't speak this month? Add your proposal here instead https://github.com/SingaporeJS/organizers/issues/40

### Organizers' todos
- [x] Create event on SingaporeJS Meetup Page
- [x] Announce on SingaporeJS Gitter, Twitter, Facebook, etc.
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

**Comment by sudheerj** [comment]
Title:
PrimeReact: Leading open source UI component library for React

Talk Description
I will be talking about what is PrimeReact, Why to choose PrimeReact,how PrimeReact makes React applications development rapid and easier with rich set of UI widgets, and ready made stunning themes to customize look and feel of websites.

Presenter:
Sudheer Jonna
https://github.com/sudheerj
https://twitter.com/sudheerjonna

Presenters Bio
Sudhee Jonna is a technology enthusiast,founder,author,speaker,reviewer,trainer,articles writer,open source contributor (PrimeFaces,PrimeFaces extensions).He is passionate about trending front end and backend technologies.
More details here
sudheerjonna.com

Duration requested:
15 mins

**Comment by jsstrn** [comment]
Hi @soelynn, does 20 April (Thu) work for you guys?

**Comment by realsoelynn** [comment]
@jsstrn yes. it works :)

**Comment by sudheerj** [comment]
@jsstrn It works for me too.

**Comment by cliener** [comment]
Title of your talk: How to Choose the Right Front-End Framework for Your Company

Talk description: During an evaluation of our core web platform at CXA Group, we decided to shift direction away from the aging existing architecture and rebuild the front-end from scratch. I'll talk about the evaluation process we used to choose a new framework.

Presenter: Chris Lienert
https://github.com/cliener
https://twitter.com/cliener

Presenter's bio: Chris started out as a web developer when Netscape ruled the world and is currently an engineering manager at health tech company CXA Group. He founded community group Singapore CSS because someone had to. 

Duration requested: 15min

Deck URL (if any): Article published https://www.sitepoint.com/choose-the-right-front-end-framework-for-your-company/
Slides TBA

**Comment by jsstrn** [comment]
@sudheerj @cliener see you guys next week for talk.js

**Comment by GIANTCRAB** [comment]
How to Choose the Right Front-End Framework for Your Company - https://youtu.be/Iw8dDe6x_LI (@cliener)

PrimeReact: UI Component Library for React - https://youtu.be/gxjS39OHpco (@sudheerj)

**Comment by jsstrn** [comment]
Thanks @GIANTCRAB
