### ISSUE TITLE
talk.js - July 2017

### ISSUE THREAD

**Issue by jsstrn** [SingaporeJS/organizers#49]
### :calendar: Details
- [ ] Event: [talk.js]()
- [x] Date: Tuesday, 18 July 2017
- [x] Hosts: @jsstrn
- [x] Venue: PayPal Singapore, Suntec Tower 5

### :speech_balloon: Talks
- [x] **Http2live - a CDN for the HTTP/2 Era** by Sebastiaan Deckers @sebdeckers 
- [x] **Tiny JS Games on Microcontrollers** by István Szmozsánszky @flaki 
- [ ] _You?_

### :seedling: Propose a talk this month
Want to speak at this month's talk? Leave a comment below with the following details:

> **Title of your talk**: insert catchy title here
>
> **Talk description**: tell us what you'd like to talk about
>
> **Presenter**: include GitHub handles where possible
>
> **Presenter's bio**: a short introduction of yourself
>
> **Duration requested**: 5min, 10min, 15min, 30min
>
> **Deck URL (if any)**: you can add this part in later

### :loudspeaker: Open announcement
Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc.

---

### :pencil: Organizers' checklist
- [x] Check available dates on [We Build SG](https://webuild.sg/)
- [x] Confirm date and venue availability with @soelynn 
- [x] Create event on [SingaporeJS Meetup Page](https://www.meetup.com/singapore-js/)
- [x] Inform @engineersftw for video recordings
- [x] Announce event on [SingaporeJS Gitter](https://gitter.im/SingaporeJS/home) and other social media platforms
- [ ] Prepare deck for event

\* _checked boxes indicate confirmed/done_

**Comment by jsstrn** [comment]
@sebdeckers talk.js July has been confirmed for Tuesday, 18 July 2017. Does this date work for you?

**Comment by flaki** [comment]
Hi! [Chinmay](@notthetup) pinged this event over to me, since I'm currently in Singapore. I'm definitely joining and also if you are still on the lookout for talks, I'm happy to present one on creating HTML5 (js+canvas 8-bit retro) games and running them on microcontrollers. :)

See talk details below, this is an updated/extended version of the [talk I gave at Hackware last week](https://twitter.com/slsoftworks/status/883269922184339457). ;)

> **Tiny JS games on microcontrollers**
> *Ever wanted to put some games on a microcontroller? No? Well, it's about time you unleashed your imagination! And in case you would be complaining about C++ right now... hold it right there, your trusty old friend, JavaScript will help you out here, too.* ;)
>
> *We will have a look at MicroCanvas a tiny HTML5 Canvas games framework for creating pixelgraphic HTML5 games that work in any web browser, desktop or mobile - and for an added bonus see how these can be compiled and flashed on tiny microcontrollers to be played on small, arduino-based custom built gaming rigs.*

My bio & contacts are [here](https://gist.github.com/flaki/70339c8f58616638b599). Talk duration should be 15 or 30 minutes, with the latter preferred. [talk.flak.is/play](http://talk.flak.is/play/) has some slides from an earlier time, which I'm going to update this week.

**Comment by realsoelynn** [comment]
@jsstrn btw i changed my github handle to @realsoelynn :)

**Comment by jsstrn** [comment]
Hi @flaki, welcome to Singapore and SingaporeJS. Looking forward to your talk next week. Thanks @notthetup!
